### ISSUE TITLE
烧CPU

### ISSUE THREAD

**Issue by laixiaohuai** [wushirenfei/web_terminal_kubernetes#1]
def run(self):
        while not self.ws.closed:

            if not self.stream.is_open():
                log.info('container stream closed')
                self.ws.close()

            try:
                if self.stream.peek_stdout():
                    stdout = self.stream.read_stdout()
                    self.ws.send(stdout)

                if self.stream.peek_stderr():
                    stderr = self.stream.read_stderr()
                    self.ws.send(stderr)
            except Exception as err:
                log.error('container stream err: {}'.format(err))
                self.ws.close()
                break

###################
这边写的while true太烧cpu，有想过做事件触发吗？我本想用epoll的，但是没有fileno属性？方便留个联系方式沟通吗？

**Comment by wushirenfei** [comment]
> def run(self):
> while not self.ws.closed:
> 
> ```
>         if not self.stream.is_open():
>             log.info('container stream closed')
>             self.ws.close()
> 
>         try:
>             if self.stream.peek_stdout():
>                 stdout = self.stream.read_stdout()
>                 self.ws.send(stdout)
> 
>             if self.stream.peek_stderr():
>                 stderr = self.stream.read_stderr()
>                 self.ws.send(stderr)
>         except Exception as err:
>             log.error('container stream err: {}'.format(err))
>             self.ws.close()
>             break
> ```
> ###################
> 这边写的while true太烧cpu，有想过做事件触发吗？我本想用epoll的，但是没有fileno属性？方便留个联系方式沟通吗？

对的，比较耗cpu，只是一个小的demo，如果想用大量生产，要优化的。QQ：1848227629，我qq号。

**Comment by wushirenfei** [comment]
参考工程首页新增内容。
